### ISSUE TITLE
The DXA_1.2_Release tag is not on the release/1.2 branch.

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-modules#14]
The DXA_1.2_Release tag is not on the release/1.2 branch. Also the release/1.2 is missing some webapp-java pom fixes from the DXA_1.2_Release tag branch.

**Comment by jhorsman** [comment]
Fixed in https://github.com/sdl/dxa-modules/pull/13

**Comment by rpannekoek** [comment]
release/1.2 branch currently represents the DXA 1.2.1 hotfix release. Is this issue still relevant or can it be closed?
