### ISSUE TITLE
DXA1.3: Core module not initialized correctly

### ISSUE THREAD

**Issue by NiclasCedermalm** [sdl/dxa-modules#15]
The core module is not initialized correctly as the spring-context.xml is placed in the wrong place in dxa-module-core. It is placed here: `src/main/resources/spring-context.xml`, but it should be placed here: `src/main/resources/META-INF/spring-context.xml`.

A workaround is to place it in the Spring context of the web application itself:

`  <!-- Temporary workaround to get the core module to load propertly -->`
`  <context:component-scan base-package="com.sdl.dxa.core"/>` 

I see that the following construct is used in the archetype to create webapps (which in this case will also find the core module's Spring beans):

`@Configuration`
`@ComponentScan(basePackages = {"com.sdl.dxa"})`
`public class WebAppConfiguration {`

But I believe that this should primarily be used for loading webapp specific Spring beans, not standard DXA modules. The modules themselves should be self-contained, so it should only be needed to drop the module JAR into the webapp and everything should be initialized correctly. And the module itself can use whatever package name it prefers.

**Comment by azarakovsky** [comment]
Well, that makes sense. Will move spring-context.xml in a core module to a right place next release.

Although, I suggest to get rid of XML configurations completely at some point of time in a future. Framework will scan com.sdl.dxa and run every single @Configuration from it. Modules themselves will then have such configurations.

**Comment by rpannekoek** [comment]
Fixed in DXA 1.4
