### ISSUE TITLE
 Header links in the navbar do not get active

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-modules#16]
The issue described in https://github.com/sdl/dxa-html-design/issues/4 needs to be fixed in the DXA Java DXA Java as well.

**Comment by jhorsman** [comment]
Fixed in https://github.com/jhorsman/dxa-modules/tree/feature/xpm-button-fix
Tested on DXA 1.2 JAVA on Tridion 2013 SP1

**Comment by jhorsman** [comment]
GitHub thinks that [this commit](https://github.com/sdl/dxa-modules/commit/5e1ebd6d28d0835cbaa5e343ed455f92c0cbf557) is related. However, this commit is from 2015 and refers to a Stash issue, not to this GitHub issue.

**Comment by rpannekoek** [comment]
Fixed in DXA 1.5
