### ISSUE TITLE
Malformed Webdav Paths When publication title contains . and _

### ISSUE THREAD

**Issue by kunalshetye** [sdl/dxa-modules#20]
Hi,

When importing MediaManager module (should be reproducible with other modules) and providing a -sitePublication override. If the parameter contains a publication name with a **. or _** the webdav path generated is not well formed.

![image](https://cloud.githubusercontent.com/assets/7836129/16333397/520802f4-39fb-11e6-9cd8-ce8cf6b183a3.png)

**Comment by rpannekoek** [comment]
TSI-1710 (internal issue ID for tracking purposes)

**Comment by rpannekoek** [comment]
Fixed in DXA 1.6.
