### ISSUE TITLE
LanguageSelector view throws error when WebRequestContext.PageModel is not set.

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-modules#24]
The [language selector view](https://github.com/sdl/dxa-modules/blob/master/webapp-net/Core/Areas/Core/Views/Entity/LanguageSelector.cshtml) in the .NET core module does an assumption that there always is a `PageModel` object in the `WebRequestContext`. This is not always the case, for example when browsing through product pages in the E-Commerce framework.

When the `WebRequestContext.PageModel` is null the LanguageSelector view causes an error in the header.

p.s. The LanguageSelector view contains a lot of logic, the language selector URLs should be resolved in a controller and added to the model so that the view is cleaner.

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12821

**Comment by rpannekoek** [comment]
Incorporated in DXA 2.2
